### ISSUE TITLE
Addon stopped working and it doesn't work anymore.

### ISSUE THREAD

**Issue by notherealmarco** [hassio-addons/addon-grafana#42]
# Problem/Motivation

> One day I found my Grafana tab on HA not working, i then noticed that the add-on was stopped. So i tried to start it, but it crashed. I then decided to uninstall and reinstall it completely, with no luck. I'll paste the logs below.

## Expected behavior

> Grafana should work?

## Actual behavior

> It crashes when loading

## Logs
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Grafana
 The open platform for beautiful analytics and monitoring
-----------------------------------------------------------
 Add-on version: 2.2.1
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.95.4
 Supervisor version: 168
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grafana.sh: executing... 
[cont-init.d] grafana.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:04:23] INFO: Starting Memcached...
[20:04:23] INFO: Starting Grafana...
panic: reflect: call of reflect.Value.Interface on zero Value
goroutine 1 [running]:
reflect.valueInterface(0x731bc, 0xfffffade, 0x0, 0x1, 0x0, 0x1)
	/usr/local/go/src/reflect/value.go:984 +0x15c
reflect.Value.Interface(...)
	/usr/local/go/src/reflect/value.go:979
github.com/grafana/grafana/vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.unmarshalScalar(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go:215 +0xd6c
runtime: unexpected return pc for runtime.main called from 0x0
stack: frame={sp:0x344e118, fp:0x344e138} stack=[0x344d000,0x344e000)
Signal handled: Terminated.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.```

**Comment by frenck** [comment]
I'm sorry, but I can reproduce this

**Comment by Wanty5883** [comment]
I got the same problem on a fresh Hassio install today. I took a while trying to figure out what is going on. So this error happend when I try to access server admin panel or profile on Grafana.

Here is the error code I have in Grafana logs
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x16248]
goroutine 377 [running]:
github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).ParseOs(0x41a6420, 0x4076f00, 0x73, 0x7315c)
	/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:284 +0xb8
github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse.func2(0x47152a0, 0x41a6420, 0x4076f00, 0x73, 0x45ed580)
	/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:233 +0x68
created by github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse
	/go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:230 +0x13c
Signal handled: Terminated.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.```

**Comment by sinclairpaul** [comment]
Apart from the failure to start I don't believe the issues are related. @Wanty5883 Please open a separate issue posting your full startup log.
